=== AnnegretJ/openDS/roadDescription.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema targetNamespace="http://opends.eu/roadDescription"
elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://opends.eu/roadDescription">
              
    <xs:element name="roadDescription" type="roadDescriptionType">
    </xs:element>


    <xs:complexType name="roadDescriptionType">
        <xs:all>
        	<xs:element name="terrain" type="terrainType" maxOccurs="1"
        		minOccurs="1">
        	</xs:element>

        	<xs:element name="segments" type="segmentsType" maxOccurs="1"
        		minOccurs="1">
        	</xs:element>
        	<xs:element name="intersections" type="intersectionsType"
        		maxOccurs="1" minOccurs="0">
        	</xs:element>

        	<xs:element name="traffic" type="trafficType" maxOccurs="1"
        		minOccurs="1">
        	</xs:element>
        </xs:all>
    </xs:complexType>

    <xs:complexType name="terrainType">
        <xs:all>
    		<xs:element name="extent" type="extentType" maxOccurs="1"
    			minOccurs="1">
    		</xs:element>
    		
    		<xs:element name="heightMap" type="heightMapType"
    			maxOccurs="1" minOccurs="1">
    		</xs:element>
    		<xs:element name="roadStartingPoint" type="roadStartingPointType" maxOccurs="1" minOccurs="1"></xs:element>
    	</xs:all>
    </xs:complexType>

	<xs:complexType name="roadStartingPointType">
    	<xs:attribute name="x" type="xs:float"></xs:attribute>
    	<xs:attribute name="z" type="xs:float"></xs:attribute>
  	 </xs:complexType>
    	
   


    <xs:complexType name="segmentsType">
    	<xs:sequence>
    		<xs:element name="segment" type="segmentType" maxOccurs="unbounded" minOccurs="1"></xs:element>
    	</xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="segmentType">
        <xs:all>
        	<xs:element name="geometries" type="geometriesType"
        		maxOccurs="1" minOccurs="1">
        	</xs:element>
            <xs:element name="laneLayout" type="laneLayoutType" maxOccurs="1" minOccurs="0">
        	</xs:element>
            <xs:element name="surface" type="surfaceType" maxOccurs="1" minOccurs="0">
            </xs:element>
            <xs:element name="successor" type="successorType" maxOccurs="1"
        		minOccurs="0">
        	</xs:element>                    </xs:all>
        
    	<xs:attribute name="id" type="xs:string"></xs:attribute>
    	<xs:attribute name="initial" type="xs:boolean"></xs:attribute>
    </xs:complexType>

    <xs:complexType name="laneLayoutType">
        <xs:all>
        	<xs:element name="noOfLanes" type="xs:int" maxOccurs="1"
        		minOccurs="0">
        	</xs:element>
        	<xs:element name="laneWidth" type="xs:float" maxOccurs="1" minOccurs="0"></xs:element>
        	<xs:element name="speedLimit" type="xs:float" maxOccurs="1"
        		minOccurs="0">
        	</xs:element>
        	<xs:element name="speedLimitOppositeDirection"
        		type="xs:float" maxOccurs="1" minOccurs="0">
        	</xs:element>
        </xs:all>
    </xs:complexType>

    <xs:complexType name="geometryType">
    	<xs:attribute name="length" type="xs:float"></xs:attribute>
    	<xs:attribute name="curvature" type="xs:float"></xs:attribute>
    </xs:complexType>

    <xs:complexType name="intersectionsType">
    	<xs:sequence>
    		<xs:element name="intersection" type="intersectionType" maxOccurs="unbounded" minOccurs="0"></xs:element>
    	</xs:sequence>
    </xs:complexType>

    <xs:complexType name="intersectionType">
    	<xs:sequence>
    		<xs:element name="outgoingSegment" type="outgoingSegmentType"
    			maxOccurs="3" minOccurs="2">
    		</xs:element>
    	</xs:sequence>

    	<xs:attribute name="id" type="xs:string"></xs:attribute>
    	<xs:attribute name="type" type="xs:string"></xs:attribute>
    </xs:complexType>

    <xs:complexType name="incomingSegmentType">
    	<xs:attribute name="ref" type="xs:string"></xs:attribute>
    </xs:complexType>

    <xs:complexType name="outgoingSegmentType">
    	<xs:attribute name="ref" type="xs:string"></xs:attribute>
    	<xs:attribute name="degree">
    		<xs:simpleType>
    			<xs:restriction base="xs:string">
    				<xs:enumeration value="-90"></xs:enumeration>
    				<xs:enumeration value="0"></xs:enumeration>
    				<xs:enumeration value="90"></xs:enumeration>
    			</xs:restriction>
    		</xs:simpleType>
    	</xs:attribute>
    </xs:complexType>

    <xs:complexType name="successorType">
        <xs:choice>
    		<xs:element name="segment" type="successorSegmentType"></xs:element>
    		<xs:element name="intersection"
    			type="successorIntersectionType">
    		</xs:element>
        </xs:choice>
    </xs:complexType>

    <xs:complexType name="successorSegmentType">
    	<xs:attribute name="ref" type="xs:string"></xs:attribute>
    </xs:complexType>

    <xs:complexType name="successorIntersectionType">
    	<xs:attribute name="ref" type="xs:string"></xs:attribute>
    </xs:complexType>

    <xs:complexType name="heightMapType">
    	<xs:attribute name="path" type="xs:string"></xs:attribute>
    	<xs:attribute name="resolution" type="xs:int"></xs:attribute>
    </xs:complexType>

    <xs:complexType name="extentType">
    	<xs:attribute name="length" type="xs:float"></xs:attribute>
    	<xs:attribute name="width" type="xs:float"></xs:attribute>
    	<xs:attribute name="maxHeight" type="xs:float"></xs:attribute>
    </xs:complexType>

    <xs:complexType name="geometriesType">
    	<xs:sequence>
    		<xs:element name="geometry" type="geometryType" maxOccurs="unbounded"
    			minOccurs="1">
    		</xs:element>
    	</xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="surfaceType">
    	<xs:sequence>
    		<xs:element name="friction" type="xs:float" maxOccurs="1" minOccurs="0"></xs:element>
    	</xs:sequence>
    </xs:complexType>

    <xs:complexType name="trafficType">
        <xs:all>
        	<xs:element name="codriver" type="codriverType"
        		maxOccurs="1" minOccurs="1">
        	</xs:element>
        	<xs:element name="vehicles" type="vehiclesType"
        		maxOccurs="1" minOccurs="0">
        	</xs:element>
        	<xs:element name="pedestrians" type="pedestriansType"
        		maxOccurs="1" minOccurs="0">
        	</xs:element>
        </xs:all>
    </xs:complexType>

    <xs:complexType name="codriverType">
        <xs:all>
        	<xs:element name="startPosition" type="onroadPositionType"
        		maxOccurs="1" minOccurs="1">
        	</xs:element>
        	<xs:element name="preferredConnections"
        		type="preferredConnectionsType" maxOccurs="1" minOccurs="0">
        	</xs:element>
        	<xs:element name="targetPosition" type="onroadPositionType"
        		maxOccurs="1" minOccurs="0">
        	</xs:element>
        	<xs:element name="terminateSimulation"
        		type="terminateSimulationType" maxOccurs="1" minOccurs="0">
        	</xs:element>
        </xs:all>
    </xs:complexType>

    <xs:complexType name="onroadPositionType">
    	<xs:attribute name="segment" type="xs:string"></xs:attribute>
    	<xs:attribute name="lane" type="xs:int"></xs:attribute>
    	<xs:attribute name="s" type="xs:float"></xs:attribute>
    </xs:complexType>

    <xs:complexType name="preferredConnectionsType">
    	<xs:sequence>
    		<xs:element name="connection" type="connectionType"
    			maxOccurs="unbounded" minOccurs="1">
    		</xs:element>
    	</xs:sequence>
    </xs:complexType>

    <xs:complexType name="connectionType">
    	<xs:attribute name="intersectionID" type="xs:string"></xs:attribute>
    	<xs:attribute name="from" type="xs:string"></xs:attribute>
    	<xs:attribute name="to" type="xs:string"></xs:attribute>
    </xs:complexType>

    <xs:complexType name="vehiclesType">
    	<xs:sequence>
    		<xs:element name="vehicle" type="vehicleType"
    			maxOccurs="unbounded" minOccurs="1">
    		</xs:element>
    	</xs:sequence>
    </xs:complexType>

    <xs:complexType name="vehicleType">
        <xs:all>
    		<xs:element name="maxSpeed" type="xs:float" maxOccurs="1" minOccurs="0">
    		</xs:element>
    		<xs:element name="startPosition" type="onroadPositionType" maxOccurs="1" minOccurs="1">
    		</xs:element>
    		<xs:element name="preferredConnections" type="preferredConnectionsType" maxOccurs="1" minOccurs="0">
    		</xs:element>
    	</xs:all>
    	<xs:attribute name="id" type="xs:string"></xs:attribute>
    </xs:complexType>

    <xs:complexType name="pedestriansType">
    	<xs:sequence>
    		<xs:element name="pedestrian" type="pedestrianType"
    			maxOccurs="unbounded" minOccurs="1">
    		</xs:element>
    	</xs:sequence>
    </xs:complexType>

    <xs:complexType name="pedestrianType">
        <xs:all>
    		<xs:element name="startPosition"
    			type="offroadPositionType" maxOccurs="1" minOccurs="1">
    		</xs:element>
    		<xs:element name="targets" type="targetsType" maxOccurs="1"
    			minOccurs="1">
    		</xs:element>
    		<xs:element name="triggerPosition" type="onroadPositionType"
    			maxOccurs="1" minOccurs="0">
    		</xs:element>
        </xs:all>
    	<xs:attribute name="id" type="xs:string"></xs:attribute>
    </xs:complexType>

    <xs:complexType name="offroadPositionType">
    	<xs:attribute name="segment" type="xs:string"></xs:attribute>
    	<xs:attribute name="lateralOffset" type="xs:float"></xs:attribute>
    	<xs:attribute name="s" type="xs:float"></xs:attribute>
    </xs:complexType>

    <xs:complexType name="targetsType">
    	<xs:sequence>
    		<xs:element name="target" type="targetType" maxOccurs="unbounded" minOccurs="1"></xs:element>
    	</xs:sequence>
    </xs:complexType>

    <xs:complexType name="targetType">
    	<xs:attribute name="lateralOffset" type="xs:float"></xs:attribute>
    	<xs:attribute name="s" type="xs:float"></xs:attribute>
    	<xs:attribute name="speed" type="xs:float"></xs:attribute>
    </xs:complexType>

    <xs:complexType name="terminateSimulationType">
    	<xs:attribute name="onTargetPositionReached"
    		type="xs:boolean">
    	</xs:attribute>
    	<xs:attribute name="onRoadEndReached" type="xs:boolean"></xs:attribute>
    </xs:complexType>
</xs:schema>

=== AnnegretJ/openDS/assets/DrivingTasks/Projects/02_scenario/02_scenario.xml
<?xml version="1.0" encoding="UTF-8"?>
<roadDescription xmlns="http://opends.eu/roadDescription"
		xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
        xsi:schemaLocation="http://opends.eu/roadDescription roadDescription.xsd">

    <terrain>
	    <extent length="200" width="200" maxHeight="30" />		
		<heightMap path="../../heightmaps/heightmap_512_002.raw" resolution="512"/>
		<roadStartingPoint x="500" z="500" />
    </terrain>
    
            
    <segments>
    	<segment id="s000" initial="true">
    		<geometries>
    			<geometry length="80" curvature="0" />
			</geometries>
			<successor>
				<intersection ref="i000" />
			</successor>
			<laneLayout>
				<noOfLanes>2</noOfLanes>
				<laneWidth>2.60</laneWidth>
				<speedLimit>70</speedLimit>
				<speedLimitOppositeDirection>70</speedLimitOppositeDirection>
			</laneLayout>
    	</segment>
		<segment id="s001" initial="false">
    		<geometries>
				<geometry length="100" curvature="0" />
			</geometries>
			<laneLayout>
				<noOfLanes>2</noOfLanes>
				<laneWidth>2.60</laneWidth>
				<speedLimit>70</speedLimit>
				<speedLimitOppositeDirection>70</speedLimitOppositeDirection>
			</laneLayout>
    	</segment>
		<segment id="s002" initial="false">
    		<geometries>
				<geometry length="150" curvature="0" />
			</geometries>
			<laneLayout>
				<noOfLanes>2</noOfLanes>
				<laneWidth>2.60</laneWidth>
				<speedLimit>70</speedLimit>
				<speedLimitOppositeDirection>70</speedLimitOppositeDirection>
			</laneLayout>
    	</segment>
		<segment id="s003" initial="false">
    		<geometries>
				<geometry length="150" curvature="0" />
			</geometries>
			<laneLayout>
				<noOfLanes>2</noOfLanes>
				<laneWidth>2.60</laneWidth>
				<speedLimit>70</speedLimit>
				<speedLimitOppositeDirection>70</speedLimitOppositeDirection>
			</laneLayout>
    	</segment>
    </segments>

	<intersections>
    	<intersection id="i000" type="crossing">
    		<outgoingSegment ref="s001" degree="-90"/>
			<outgoingSegment ref="s002" degree="0"/>
			<outgoingSegment ref="s003" degree="90" /> 
    	</intersection>
    </intersections>
	
	<traffic>
		<codriver>
			<startPosition segment="s000" lane="-1" s="10" />
			<preferredConnections>
        		<connection intersectionID="i000" from="s000" to="s002" />
        	</preferredConnections>
			<targetPosition segment="s002" lane="-1" s="30"/>
			<terminateSimulation onTargetPositionReached="true" onRoadEndReached="true" />
		</codriver>
		<vehicles>
			<vehicle id="car01">
				<maxSpeed>45</maxSpeed>
				<startPosition segment="s001" lane="1" s="50" />
				<preferredConnections>
					<connection intersectionID="i000" from="s001" to="s003" />
				</preferredConnections>
			</vehicle>
			<vehicle id="car02">
				<maxSpeed>70</maxSpeed>
				<startPosition segment="s003" lane="1" s="35" />
				<preferredConnections>
					<connection intersectionID="i000" from="s003" to="s001" />
				</preferredConnections>
			</vehicle>
		</vehicles>
	</traffic>
    
    
</roadDescription>

=== AnnegretJ/openDS/roadDescription.xml
<?xml version="1.0" encoding="UTF-8"?>
<roadDescription xmlns="http://opends.eu/roadDescription"
		xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
        xsi:schemaLocation="http://opends.eu/roadDescription roadDescription.xsd">

    <terrain>	
		<extent length="500" width="500" maxHeight="15" />		
		<heightMap path="Assets/test6.raw" resolution="2048"/>
		<roadStartingPoint x="100" z="100" />
    </terrain>
	
	     
    <segments>
    	<segment id="s000" initial="true">
    		<geometries>
    			<geometry length="50" curvature="0" />
				<geometry length="50" curvature="-60" />
			</geometries>
			<successor>
				<segment ref="s001" />
			</successor>
			<laneLayout>
				<noOfLanes>2</noOfLanes>
				<laneWidth>2.60</laneWidth>
				<speedLimit>80</speedLimit>
				<speedLimitOppositeDirection>80</speedLimitOppositeDirection>
			</laneLayout>
			<surface>
				<friction>1.2</friction>
			</surface>
    	</segment>
		
    	<segment id="s001" initial="false">
    		<geometries>
				<geometry length="50" curvature="0" />
				<geometry length="30" curvature="50" />
				<geometry length="50" curvature="0" />
			</geometries>
			<successor>
				<intersection ref="i001" />
			</successor>
			<laneLayout>
				<noOfLanes>2</noOfLanes>
				<laneWidth>2.60</laneWidth>
				<speedLimit>80</speedLimit>
				<speedLimitOppositeDirection>80</speedLimitOppositeDirection>
			</laneLayout>
			<surface>
				<friction>1.2</friction>
			</surface>
    	</segment>
    
		<segment id="s002" initial="false">
    		<geometries>
    			<geometry length="100" curvature="0" />
				<geometry length="100" curvature="90" />
			</geometries>
			<laneLayout>
				<noOfLanes>2</noOfLanes>
				<laneWidth>2.60</laneWidth>
				<speedLimit>80</speedLimit>
				<speedLimitOppositeDirection>80</speedLimitOppositeDirection>
			</laneLayout>
			<surface>
				<friction>1.2</friction>
			</surface>
    	</segment>
		
		<segment id="s003" initial="false">
    		<geometries>
    			<geometry length="100" curvature="0" />
				<geometry length="50" curvature="90" />
			</geometries>
			<successor>
				<intersection ref="i002" />
			</successor>
			<laneLayout>
				<noOfLanes>2</noOfLanes>
				<laneWidth>2.60</laneWidth>
				<speedLimit>80</speedLimit>
				<speedLimitOppositeDirection>80</speedLimitOppositeDirection>
			</laneLayout>
			<surface>
				<friction>1.2</friction>
			</surface>
    	</segment>
		
		<segment id="s004" initial="false">
    		<geometries>
    			<geometry length="100" curvature="0" />
				<geometry length="100" curvature="-90" />
				<geometry length="100" curvature="0" />
			</geometries>
			<laneLayout>
				<noOfLanes>2</noOfLanes>
				<laneWidth>2.60</laneWidth>
				<speedLimit>80</speedLimit>
				<speedLimitOppositeDirection>80</speedLimitOppositeDirection>
			</laneLayout>
			<surface>
				<friction>1.2</friction>
			</surface>
    	</segment>
				
		<segment id="s010" initial="false">
    		<geometries>
    			<geometry length="50" curvature="0" />
			</geometries>
			<laneLayout>
				<noOfLanes>2</noOfLanes>
				<laneWidth>2.60</laneWidth>
				<speedLimit>80</speedLimit>
				<speedLimitOppositeDirection>80</speedLimitOppositeDirection>
			</laneLayout>
			<surface>
				<friction>1.2</friction>
			</surface>
    	</segment> 
		
		<!--
		<segment id="s011" initial="false">
    		<geometries>
    			<geometry length="40" curvature="0" />
			</geometries>
			<laneLayout>
				<noOfLanes>2</noOfLanes>
				<laneWidth>2.60</laneWidth>
				<speedLimit>80</speedLimit>
				<speedLimitOppositeDirection>80</speedLimitOppositeDirection>
			</laneLayout>
			<surface>
				<friction>1.2</friction>
			</surface>
    	</segment> 
		-->
		
		<segment id="s012" initial="false">
    		<geometries>
    			<geometry length="30" curvature="0" />
			</geometries>
			<laneLayout>
				<noOfLanes>2</noOfLanes>
				<laneWidth>2.60</laneWidth>
				<speedLimit>80</speedLimit>
				<speedLimitOppositeDirection>80</speedLimitOppositeDirection>
			</laneLayout>
			<surface>
				<friction>1.2</friction>
			</surface>
    	</segment> 
    </segments>
    
    
	
    <intersections>
    	<intersection id="i001" type="crossing">
    		<outgoingSegment ref="s002" degree="-90"/>
			<outgoingSegment ref="s003" degree="0"/>
			<outgoingSegment ref="s004" degree="90" /> 
    	</intersection>
    	
    	 <intersection id="i002" type="crossing">
    		<outgoingSegment ref="s010" degree="-90" />
			<outgoingSegment ref="s012" degree="90" /> 
		</intersection>
    </intersections>
	
    
    <traffic>
		<codriver>
			<startPosition segment="s000" lane="-1" s="0" />
			<preferredConnections>
        		<connection intersectionID="i001" from="s000" to="s002" />
        	</preferredConnections>
        	<targetPosition segment="s004" lane="-1" s="22"/>
        	<terminateSimulation onTargetPositionReached="true" onRoadEndReached="true" />
		</codriver>
		<vehicles>
			<vehicle id="car01">
				<maxSpeed>50</maxSpeed>
				<startPosition segment="s002" lane="1" s="0" />
				<preferredConnections>
					<connection intersectionID="i001" from="s002" to="s003" />
				</preferredConnections>
			</vehicle>
		</vehicles>
		<pedestrians>
			<pedestrian id="pedestrian01" >
    			<startPosition segment="s000" lateralOffset="-5.3" s="0" />
    			<targets>
        		 	<target lateralOffset="-5.3" s="40" speed="4.1" />
        			<target lateralOffset="5.3" s="60" speed="2.8" />
        			<target lateralOffset="5.3" s="80" speed="4.3" />
    			</targets>
    			<triggerPosition segment="s001" lane="-1" s="10" />
			</pedestrian>
			<pedestrian id="pedestrian02" >
    			<startPosition segment="s001" lateralOffset="-5.3" s="0" />
    			<targets>
        			<target lateralOffset="-5.3" s="30" speed="4.1" />
        			<target lateralOffset="5.3" s="30" speed="2.8" />
        			<target lateralOffset="5.3" s="60" speed="4.3" />
        			<target lateralOffset="-5.3" s="60" speed="1.5" />
    			</targets>
    			<triggerPosition segment="s002" lane="-1" s="10" />
			</pedestrian>
		</pedestrians>
	</traffic>
	
</roadDescription>
