=== AnnegretJ/openDS/assets/DrivingTasks/Schema/interaction.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema targetNamespace="http://opends.eu/drivingtask/interaction"
elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://opends.eu/drivingtask/interaction">

    <xs:element name="interaction">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="0" maxOccurs="1" name="activities" type="activities"/>
                <xs:element minOccurs="0" maxOccurs="1" name="triggers" type="triggers"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="triggers">
        <xs:sequence>
            <xs:element minOccurs="0" maxOccurs="unbounded" name="trigger" type="trigger"/>
        </xs:sequence>
    </xs:complexType>
   
    <xs:complexType name="trigger">
        <xs:sequence>
            <xs:element name="activities" type="activities"/>
            <xs:element name="condition" type="conditionType" />
        </xs:sequence>
        <xs:attribute name="id" type="xs:string"/>
        <xs:attribute name="priority" type="xs:integer"/>
    </xs:complexType>

    <xs:complexType name="activities">
        <xs:sequence>
            <xs:element minOccurs="0" maxOccurs="unbounded" name="activity" type="activity"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="activity">
        <xs:sequence>
            <xs:element minOccurs="0" maxOccurs="unbounded" name="action" type="action"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:string"/>
        <xs:attribute name="ref" type="xs:string"/>
    </xs:complexType>

    <xs:complexType name="action">
        <xs:sequence>
            <xs:element minOccurs="0" maxOccurs="unbounded" name="parameter" type="parameter"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:string"/>
        <xs:attribute name="delay" type="xs:float"/>
        <xs:attribute name="repeat" type="xs:integer"/>
    </xs:complexType>

    <xs:complexType name="parameter">
        <xs:attribute name="value" type="xs:string" use="required" />
        <xs:attribute name="name" type="xs:string" use="required" />
    </xs:complexType>

    <xs:complexType name="conditionType">
        <xs:sequence>


            <xs:element name="pressKey" type="pressKeyType" maxOccurs="unbounded" minOccurs="0">
        	</xs:element>
            <xs:element name="pressButton" type="pressButtonType" maxOccurs="unbounded" minOccurs="0">
        	</xs:element>
            <xs:element name="pressPedal" type="pressPedalType" maxOccurs="unbounded" minOccurs="0">
        	</xs:element>
            <xs:element name="collideWith" type="collideWithType" maxOccurs="unbounded" minOccurs="0">
        	</xs:element>
            <xs:element name="openDrivePos" type="openDrivePosType" maxOccurs="unbounded" minOccurs="0">
        	</xs:element>
            <xs:element name="remote" type="remoteType" maxOccurs="unbounded" minOccurs="0">
        	</xs:element>
            <xs:element name="cameraWaypoint" type="cameraWaypointType" maxOccurs="unbounded" minOccurs="0">
        		</xs:element>
        </xs:sequence>

    </xs:complexType>

    <xs:complexType name="pressKeyType">
    	<xs:sequence>
    		<xs:element name="key" type="xs:string" maxOccurs="1" minOccurs="1"></xs:element>
    	</xs:sequence>
    </xs:complexType>

    <xs:complexType name="pressButtonType">
        <xs:all>
    		<xs:element name="deviceID" type="xs:int" maxOccurs="1" minOccurs="0">
    		</xs:element>
    		<xs:element name="button" type="xs:int" maxOccurs="1" minOccurs="1"></xs:element>
    	</xs:all>
    </xs:complexType>

    <xs:complexType name="pressPedalType">
        <xs:all>
    		<xs:element name="pedal" type="xs:string" maxOccurs="1" minOccurs="1">
    		</xs:element>
    		<xs:element name="triggeringThreshold" type="xs:float" maxOccurs="1" minOccurs="0"></xs:element>
    	</xs:all>
    </xs:complexType>

    <xs:complexType name="collideWithType">
    	<xs:sequence>
    		<xs:element name="modelID" type="xs:string" maxOccurs="1" minOccurs="1"></xs:element>
    	</xs:sequence>
    </xs:complexType>

    <xs:complexType name="openDrivePosType">
        <xs:all>
    		<xs:element name="trafficCarID" type="xs:string" maxOccurs="1" minOccurs="0">
    		</xs:element>
    		<xs:element name="roadID" type="xs:string" maxOccurs="1" minOccurs="1"></xs:element>
    		<xs:element name="lane" type="xs:int" maxOccurs="1" minOccurs="0"></xs:element>
    		<xs:element name="s" type="xs:double" maxOccurs="1" minOccurs="1"></xs:element>
    	</xs:all>
    </xs:complexType>

    <xs:complexType name="remoteType">
    	<xs:sequence>
    		<xs:element name="triggerID" type="xs:string" maxOccurs="1" minOccurs="1"></xs:element>
    	</xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="cameraWaypointType">
    	<xs:sequence>
    		<xs:element name="waypointID" type="xs:string" maxOccurs="1" minOccurs="1"></xs:element>
    	</xs:sequence>
    </xs:complexType>
</xs:schema>

=== AnnegretJ/openDS/assets/DrivingTasks/Projects/ParisTraffic/interaction.xml
<?xml version="1.0" encoding="UTF-8"?>
<interaction xmlns="http://opends.eu/drivingtask/interaction"
		xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
        xsi:schemaLocation="http://opends.eu/drivingtask/interaction ../../Schema/interaction.xsd">


	<activities>
		<activity id="movePedestrianCrossing_1">
			<action id="manipulateObject" delay="0" repeat="0">
				<parameter name="id" value="PedestrianCrossing_1" />
				<parameter name="setTranslationX" value="-74.77681" />
				<parameter name="setTranslationY" value="-0.26786697" />
				<parameter name="setTranslationZ" value="5.0" />
			</action>
		</activity>
		<activity id="movePedestrianCrossing_1Back">
			<action id="manipulateObject" delay="0" repeat="0">
				<parameter name="id" value="PedestrianCrossing_1" />
				<parameter name="setTranslationX" value="-69.77681" />
				<parameter name="setTranslationY" value="-0.26786697" />
				<parameter name="setTranslationZ" value="5.0" />
			</action>
		</activity>
		<activity id="moveCar1">
			<action id="moveTraffic" delay="0" repeat="4">
				<parameter name="trafficObjectID" value="car1" />
				<parameter name="wayPointID" value="1WayPoint_6" />
			</action>
		</activity>
		<activity id="resumeSim">
			<action id="resumeSimulation" delay="0" repeat="0">
			</action>
		</activity>
	</activities>
	
	<triggers>
	</triggers>
	
</interaction>

=== AnnegretJ/openDS/assets/DrivingTasks/Projects/init_drive/interaction.xml
<?xml version="1.0" encoding="UTF-8"?>
<interaction xmlns="http://opends.eu/drivingtask/interaction"
		xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
        xsi:schemaLocation="http://opends.eu/drivingtask/interaction ../../Schema/interaction.xsd">

	<activities>
	</activities>
	
	<triggers>
		<trigger id="start_pedestrian01" priority="1">
			<activities>
				<activity id="start_pedestrian01">
					<action id="moveTraffic" delay="0" repeat="0">
						<parameter name="trafficObjectID" value="pedestrian01" />
						<parameter name="enabled" value="true" />
					</action>
				</activity>
			</activities>
			<condition>
				<openDrivePos>
					<roadID>s000</roadID>
					<lane>-1</lane>
					<s>32.0</s>
				</openDrivePos>
			</condition>
		</trigger>
		<trigger id="stop_car01_trigger" priority="1">
			<activities>
				<activity id="stop_car01">
					<action id="moveTraffic" delay="0" repeat="0">
						<parameter name="trafficObjectID" value="car01" />
						<parameter name="engineOn" value="false" />
					</action>
				</activity>
			</activities>
			<condition>
				<openDrivePos>
					<roadID>s001</roadID>
					<lane>-1</lane>
					<s>50.0</s>
				</openDrivePos>
			</condition>
		</trigger>
	</triggers>
	
</interaction>

=== AnnegretJ/openDS/assets/DrivingTasks/Projects/pedestrian/interaction.xml
<?xml version="1.0" encoding="UTF-8"?>
<interaction xmlns="http://opends.eu/drivingtask/interaction"
		xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
        xsi:schemaLocation="http://opends.eu/drivingtask/interaction ../../Schema/interaction.xsd">

	<activities>
	</activities>
	
	<triggers>
		<trigger id="start_pedestrian01" priority="1">
			<activities>
				<activity id="start_pedestrian01">
					<action id="moveTraffic" delay="0" repeat="0">
						<parameter name="trafficObjectID" value="pedestrian01" />
						<parameter name="enabled" value="true" />
					</action>
				</activity>
			</activities>
			<condition>
				<openDrivePos>
					<roadID>s000</roadID>
					<lane>-1</lane>
					<s>32.0</s>
				</openDrivePos>
			</condition>
		</trigger>
		<trigger id="shutDownOnTargetPosition" priority="1">
			<activities>
				<activity id="shutDownOnTargetPosition">
					<action id="shutDownSimulation" delay="0" repeat="0">
					</action>
				</activity>
			</activities>
			<condition>
				<openDrivePos>
					<roadID>s000</roadID>
					<lane>-1</lane>
					<s>340.0</s>
				</openDrivePos>
			</condition>
		</trigger>
	</triggers>
	
</interaction>

=== AnnegretJ/openDS/assets/DrivingTasks/Projects/01_scenario/interaction.xml
<?xml version="1.0" encoding="UTF-8"?>
<interaction xmlns="http://opends.eu/drivingtask/interaction"
		xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
        xsi:schemaLocation="http://opends.eu/drivingtask/interaction ../../Schema/interaction.xsd">

	<activities>
	</activities>
	
	<triggers>
		<trigger id="shutDownOnTargetPosition" priority="1">
			<activities>
				<activity id="shutDownOnTargetPosition">
					<action id="shutDownSimulation" delay="0" repeat="0">
					</action>
				</activity>
			</activities>
			<condition>
				<openDrivePos>
					<roadID>s002</roadID>
					<lane>-1</lane>
					<s>30.0</s>
				</openDrivePos>
			</condition>
		</trigger>
		<trigger id="shutDownOnRoadEnd_s001_lane_-1" priority="1">
			<activities>
				<activity id="shutDownOnRoadEnd_s001_lane_-1">
					<action id="shutDownSimulation" delay="0" repeat="0">
					</action>
				</activity>
			</activities>
			<condition>
				<openDrivePos>
					<roadID>s001</roadID>
					<lane>-1</lane>
					<s>100.988</s>
				</openDrivePos>
			</condition>
		</trigger>
		<trigger id="shutDownOnRoadEnd_s002_lane_-1" priority="1">
			<activities>
				<activity id="shutDownOnRoadEnd_s002_lane_-1">
					<action id="shutDownSimulation" delay="0" repeat="0">
					</action>
				</activity>
			</activities>
			<condition>
				<openDrivePos>
					<roadID>s002</roadID>
					<lane>-1</lane>
					<s>149.99</s>
				</openDrivePos>
			</condition>
		</trigger>
		<trigger id="shutDownOnRoadEnd_s003_lane_-1" priority="1">
			<activities>
				<activity id="shutDownOnRoadEnd_s003_lane_-1">
					<action id="shutDownSimulation" delay="0" repeat="0">
					</action>
				</activity>
			</activities>
			<condition>
				<openDrivePos>
					<roadID>s003</roadID>
					<lane>-1</lane>
					<s>150.988</s>
				</openDrivePos>
			</condition>
		</trigger>

	</triggers>
	
</interaction>
